### ISSUE TITLE
Diseñar pantalla "Conversaciones"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-ios#1]
Crear un layout que se vea similar a la siguiente imagen, la cual muestra el listado de conversaciones asociadas a la categoría "Unassigned":

![](https://www.helpscout.net/images/blog/2016/jan/help-scout-iphone-conversations.png)

**Comment by fmendoza-gstd** [comment]
@aromero-gstd 
Corregir los siguientes errores:

![captura de pantalla 2016-12-12 a las 9 40 35](https://cloud.githubusercontent.com/assets/22350992/21105318/65540b20-c04f-11e6-8a0f-cec7186217b1.png)

**Comment by aromero-gstd** [comment]
<img width="494" alt="captura de pantalla 2016-12-12 a las 11 55 26 a m" src="https://cloud.githubusercontent.com/assets/22351435/21110220/f4e5b632-c061-11e6-990b-adfdf6d397bd.png">
<img width="319" alt="captura de pantalla 2016-12-12 a las 11 55 04 a m" src="https://cloud.githubusercontent.com/assets/22351435/21110221/f4f622ce-c061-11e6-9012-003ca36134d4.png">

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
