### ISSUE TITLE
Diseñar pantalla "Detalle Conversación"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-ios#2]
Crear layout que se vea similar a la siguiente imagen, la cual muestra el detalle de una conversación:

<img src="https://www.helpscout.net/images/mobile/app--screen-2.png" width="400"/>

**Comment by aromero-gstd** [comment]
<img width="286" alt="captura de pantalla 2016-12-21 a las 10 10 59 a m" src="https://cloud.githubusercontent.com/assets/22351435/21396487/149a6c1a-c766-11e6-8dd6-4e293f6bd857.png">
<img width="318" alt="captura de pantalla 2016-12-21 a las 10 10 48 a m" src="https://cloud.githubusercontent.com/assets/22351435/21396488/149c4652-c766-11e6-885c-45b7ac782065.png">

**Comment by aromero-gstd** [comment]
![img_3259](https://cloud.githubusercontent.com/assets/22351435/21397917/2117f4d0-c76b-11e6-8935-fd05407267a7.jpg)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
