### ISSUE TITLE
Diseñar pantalla "Mailboxes"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-ios#4]
Crear un layout que se vea similar a la siguiente imagen, la cual muestra el listado de mailboxes:

![](http://a3.mzstatic.com/us/r30/Purple62/v4/4b/b6/20/4bb6202b-f88a-2af4-c866-20fa9cff0ced/screen696x696.jpeg)

**Comment by aromero-gstd** [comment]
<img width="326" alt="captura de pantalla 2016-12-13 a las 12 58 24 p m" src="https://cloud.githubusercontent.com/assets/22351435/21154419/f6484256-c133-11e6-8ebc-1d3edc02fef4.png">
<img width="319" alt="captura de pantalla 2016-12-13 a las 12 57 38 p m" src="https://cloud.githubusercontent.com/assets/22351435/21154418/f647ce7a-c133-11e6-8808-2c8453daf62e.png">

**Comment by fmendoza-gstd** [comment]
@aromero-gstd 
Corregir las siguientes observaciones:

<img width="326" alt="f6484256-c133-11e6-8ebc-1d3edc02fef4" src="https://cloud.githubusercontent.com/assets/22350992/21154748/1ea62cd0-c135-11e6-8b10-a4e9aff0dab4.png">

**Comment by aromero-gstd** [comment]
<img width="323" alt="captura de pantalla 2016-12-14 a las 11 06 47 a m" src="https://cloud.githubusercontent.com/assets/22351435/21192252/871bb93e-c1ed-11e6-9ec8-15fb6149c9d0.png">
<img width="325" alt="captura de pantalla 2016-12-14 a las 11 06 59 a m" src="https://cloud.githubusercontent.com/assets/22351435/21192251/871abade-c1ed-11e6-8715-fbb1bc34baa9.png">

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
