### ISSUE TITLE
Diseñar pantalla "Log In"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-ios#5]
Crear layout que se vea similar a la siguiente imagen

![2117f4d0-c76b-11e6-8935-fd05407267a7](https://cloud.githubusercontent.com/assets/22350992/21397945/3d7cc63c-c76b-11e6-999a-ccb6b88dcd92.jpg)
:

**Comment by aromero-gstd** [comment]
<img width="316" alt="captura de pantalla 2016-12-21 a las 12 36 43 p m" src="https://cloud.githubusercontent.com/assets/22351435/21401504/367b03f8-c77a-11e6-93bc-520eb4ca1654.png">

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
