### ISSUE TITLE
Crear pantalla "Reply"

### ISSUE THREAD

**Issue by fmendoza-gstd** [fmendoza-gstd/hscout-ios#6]
Crear layout que se vea similar a la siguiente imagen:

![](http://a5.mzstatic.com/us/r30/Purple71/v4/de/f3/eb/def3eb8d-28e5-75d2-d635-36af21e775c4/screen696x696.jpeg)

**Comment by aromero-gstd** [comment]
![img_3262](https://cloud.githubusercontent.com/assets/22351435/21403138/2bbd725a-c781-11e6-8222-9bef041e9345.jpg)

**Comment by fmendoza-gstd** [comment]
Good Job! 👍
